# Generated by Django 4.1.4 on 2023-01-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bookings_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
            preserve_default=False,
        ),
    ]
